services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_PATH=/app/database/data.db
      - PORT=8080
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend